#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ResourceDroidForSWLCG.Resource", IsApplication=true)]

namespace ResourceDroidForSWLCG
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int contents = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int dark_side_factions = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int faction_imperial_navy = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int faction_jedi = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int faction_rebel_alliance = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int faction_scum_and_villainy = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int faction_sith = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int faction_spies_and_smugglers = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int force_alignment = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int light_side_factions = 2131034120;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int botf_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int botf_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int deathstar_100x100 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int deathstar_150x150 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int deathstar_200x200 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int deathstar_300x300 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int deathstar_400x400 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int deckbox = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int focus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int refresh = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rulebook = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int about = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int deathStarDial = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int deckbox = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int decreaseReserve = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int faction = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int forceAlignment = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int forceToken = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int gridView1 = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int increaseReserve = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int navigation = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int relativeLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int reserve = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int reset = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int resources = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int rules = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int rulesMenu = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int textView = 2131099666;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int textView2 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int textView3 = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Deckbox = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Menu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Rule = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Rules = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000c
			public const int ApplicationName = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int Hello = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int advancedConcepts = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int cardAbilities = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int cardAnatomy = 2130968577;
			
			// aapt resource value: 0x7f04000e
			public const int ds_force = 2130968590;
			
			// aapt resource value: 0x7f040009
			public const int errata = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int gameOverview = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int gameOverviewText = 2130968586;
			
			// aapt resource value: 0x7f040012
			public const int imperial_navy = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int jedi = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int ls_force = 2130968589;
			
			// aapt resource value: 0x7f040017
			public const int max_death_star = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int min_death_star = 2130968598;
			
			// aapt resource value: 0x7f040007
			public const int otherRules = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int playingTheGame = 2130968579;
			
			// aapt resource value: 0x7f04000f
			public const int rebel_alliance = 2130968591;
			
			// aapt resource value: 0x7f040005
			public const int resolvingAnEngagement = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int resources = 2130968580;
			
			// aapt resource value: 0x7f040014
			public const int scum_and_villainy = 2130968596;
			
			// aapt resource value: 0x7f040002
			public const int setup = 2130968578;
			
			// aapt resource value: 0x7f040013
			public const int sith = 2130968595;
			
			// aapt resource value: 0x7f040011
			public const int spies_and_smugglers = 2130968593;
			
			// aapt resource value: 0x7f040015
			public const int starting_reserve = 2130968597;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
